from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
import json
import urllib.request

from models.schemas import QueryRequest, QueryResponse, SourceChunk

from services.embedder import embed_query
from services.vector_store import search_chunks
from services.llm import answer_question, stream_answer, answer_image_doc
from services.firebase_store import get_doc_record, get_session, save_session
from datetime import datetime, timezone
import uuid

router = APIRouter(
    prefix="/query",
    tags=['query']
)

async def _retrieve(req: QueryRequest) -> tuple:
  """
  Shared retrieval logic for both single-doc and multi-doc queries.
  if -> doc_id provided : single doc query, if doc_ids provided OR no doc_id -> multi-doc query
  """
  
  doc_id = req.doc_id
  doc_ids = getattr(req, 'doc_ids', None)
  
  category = 'general'
  is_image_doc = False
  doc_record = None

  if doc_id:
    doc_record = get_doc_record(doc_id)
    if not doc_record:
      raise HTTPException(status_code=404, detail=f"Document '{doc_id}' not found")
    category = doc_record.get('category', 'general')
    is_image_doc = doc_record.get('is_image_doc', False)

  if is_image_doc:
    return [], category, True, doc_record

  query_vector = embed_query(req.question)

  raw_chunks = search_chunks(
    query_vector=query_vector,
    doc_id=doc_id,
    doc_ids=doc_ids,
  )

  if not raw_chunks:
    raise HTTPException(status_code=404, detail="No relevant chunks found for the query.")

  return raw_chunks, category, False, doc_record

def _format_sources(raw_chunks: list) -> list[SourceChunk]:
  """
  Convert raw chunk data from vector store into the SourceChunk format defined in our Pydantic models.
  This ensures a consistent structure for the LLM prompt and the API response.
  """
  sources = []
  for chunk in raw_chunks:
    source = SourceChunk(
      text=chunk['text'],
      page=chunk.get('page', None),
      score=chunk['score'],
      doc_id=chunk['doc_id'],
      filename=chunk['filename'],
    )
    sources.append(source)
  return sources

# POST /query -> returns the full answer at once, not streaming


@router.post("/", response_model=QueryResponse)
async def query(req: QueryRequest):
  raw_chunks, category, is_image_doc, doc_record = await _retrieve(req)

  if is_image_doc:
    storage_url = doc_record.get('storage_url') if doc_record else None
    if not storage_url:
      raise HTTPException(status_code=404, detail="Image document URL not found.")

    try:
      with urllib.request.urlopen(storage_url) as response:
        image_bytes = response.read()
    except Exception as e:
      raise HTTPException(status_code=500, detail=f"Failed to fetch image document: {str(e)}")

    answer = answer_image_doc(
      question=req.question,
      image_bytes=image_bytes,
      category=category,
    )

    return QueryResponse(
      answer=answer,
      sources=[],
      doc_category=category,
      model_used='gemini-2.5-flash',
    )
  
  answer = answer_question(
    question=req.question,
    chunks=raw_chunks,
    category=category,
    conversation_history=req.conversation_history or [],
  )
  
  return QueryResponse(
    answer=answer,
    sources=_format_sources(raw_chunks),
    doc_category=category,
    model_used='gemini-2.5-flash',
  )
  
  
  # POST /query/stream -> streams the answer token by token as it's generated by the LLM
  # SSE -> server sent Events Stream
  
@router.post("/stream")
async def query_stream(req: QueryRequest):
  raw_chunks, category, is_image_doc, _ = await _retrieve(req)

  if is_image_doc:
    raise HTTPException(
      status_code=400,
      detail="Streaming is not supported for image-only documents. Use /query instead."
    )
  
  sources_payload = [
    {
      'text' : chunk['text'][:300] + '...' if len(chunk['text']) > 300 else chunk['text'],
      'page': chunk.get('page', None),
      'score': chunk['score'],
      'doc_id': chunk['doc_id'],
      'filename': chunk['filename'],
    }
    for chunk in raw_chunks
  ]
  async def answer_generator():
    try:
      async for token in stream_answer(
        question=req.question,
        chunks=raw_chunks,
        category=category,
        conversation_history=req.conversation_history or [],
      ):
        # SSE format: "data: {token}\n\n
        # The double newline indicates the end of one message
        event = json.dumps({
          'type': 'token',
          'content': token,
        })
        yield f"data: {event}\n\n"
      
      event = json.dumps({
        'type': 'end',
        'content': sources_payload
      })
      yield f"data: {event}\n\n"
      
      event = json.dumps({
        'type' : 'metadata',
        'category' : category,
      })
      yield f"data: {event}\n\n"
    except Exception as e:
      # if anything goes wrong, send an error event
      event = json.dumps({
        'type': 'error',
        'content': str(e),
      })
      yield f"data: {event}\n\n"
      
  return StreamingResponse(answer_generator(), media_type="text/event-stream", headers={
    # tell proxies and CDNs not to cache this response
    "Cache-Control": "no-cache",
    "X-Accel-Buffering": "no",  # for nginx: disable 
  })
  
  
  # POST /query/ multi
  
@router.post("/multi")
async def query_multi(req: QueryRequest):
   """
   Ask a question across multiple documents. The request can include either a list of doc_ids or no doc_id at all (which means search across all docs).
    
    
   """
    
   doc_ids = getattr(req, 'doc_ids', None) or []
   if not doc_ids:
     raise HTTPException(
       status_code=400,
       detail="doc_ids list is required for multi-document queries"
     )
   query_vector = embed_query(req.question)
   raw_chunks = search_chunks(
     query_vector=query_vector,
     doc_ids=doc_ids,
   )
    
   if not raw_chunks:
     raise HTTPException(status_code=404, detail="No relevant content found across the specified documents.")
    
   answer = answer_question(
      question=req.question,
      chunks=raw_chunks,
      category='general',
      conversation_history=req.conversation_history or [],
    )
    
    # group souurces by document so flutter can show
    # which chunks came from which document
    
   sources_by_doc = {}
   for chunk in raw_chunks:
      fname = chunk['filename']
      if fname not in sources_by_doc:
        sources_by_doc[fname] = []
      sources_by_doc[fname].append(chunk)
      
   return {
     'answer': answer,
     'sources': _format_sources(raw_chunks),
     'sources_by_doc': sources_by_doc,
     'doc_count': len(sources_by_doc),
     'total_chunks': len(raw_chunks),
     'model_used': 'gemini-2.5-flash',
   }